### ISSUE TITLE
Why performance dropped a lot?

### ISSUE THREAD

**Issue by lucasjinreal** [SJTU-IPADS/PowerInfer#31] opened 2023-12-21 02:20 UTC
Is it worth?

**Comment by YixinSong-e** [comment] 2023-12-21 02:22
Can you provide a specific description of the model you are running and the relevant parameters?

**Comment by lucasjinreal** [comment] 2023-12-21 02:25
![8a4c3a4bcc042f7e480c00b94727f49](https://github.com/SJTU-IPADS/PowerInfer/assets/21303438/c7138f13-04ed-499a-8aa9-b20a170f81e9)

**Comment by YixinSong-e** [comment] 2023-12-21 02:28
OK. Regarding the issue of model quality, the sparseLLM team only fine tuned 5B on the original model. This almost restored accuracy on models 7B and 13B, but not on models 70B, and we may need more finetune. PowerInfer is just a work that focuses on the sparse activation phenomenon caused by ReLU activation and utilizes this phenomenon. In the future, we hope to have better support for the 70B model.

**Comment by lucasjinreal** [comment] 2023-12-21 02:32
In case of it need further finetuning the model, the time-cost and the gain not very balanced compare with just quantization.

**Comment by YixinSong-e** [comment] 2023-12-21 02:36
Perhaps in the future, there will be direct activation functions such as ReLU, ReGLU, and other LLMs. If we can draw attention to the efficiency of sparse activation caused by activation functions, we would also be very happy.

**Comment by YixinSong-e** [comment] 2023-12-21 16:21
So if there are no more issues, this issue will be closed in one hour. Thank you for your interest.

**Closed by YixinSong-e** 2023-12-21 16:21 UTC
